### PR TITLE
Upgrade pushpickup from Meteor 0.8.2 to 1.0.2.1 completed

### LINKED ISSUE #161: Upgrade to Meteor 1.0
@stewartmccoy, we need to migrate to meteor 1.0 before doing any new development.

### PR DESCRIPTION
**Pull request by nickytonline**
@stewartmccoy, @sgup, @dwinston, pushpickup has been upgraded to Meteor 1.0.2.1. I'll close #161 once @stewartmccoy has merged to master. Please note that there is an outstanding issue with SSL, issue #160, so if you decide to put the code back online serving it over SSL, this will need to be addressed.

### CODE REVIEW

**Comment by stewartmccoy** [comment]
@nickytonline to clarify, does #160 need to be resolved before master can be deployed or are we currently working around that issue?

**Comment by stewartmccoy** [comment]
@nickytonline I should have fetched your upgrade branch and tested it locally first before merging to master, but I didn't :kissing: I say that because the upgrade won't load for my locally. First, bootstrap3-less is still specified as a package and it's not recognized. Even if I remove it from .meteor/packages, I get another error because main.less is trying to import variables.import.less and mixins.import.less. I saw that you added both the nemo64:bootstrap package and less package, so I assume that will cover the removal of bootstrap3-less. However, I think we still need to add custom.bootstrap.json in client/lib. I tried that, and set all the options to true (since that was roughly what we loaded in main.less), but the style doesn't render properly. My point is, do you think you could get the boostrap3 and less packages working so that they render the style as it's currently rendered on production?

**Comment by nickytonline** [comment]
@stewartmccoy I'll check it out. It's weird though.  Locally for me everything is working fine in terms of style. Can you run ```meteor upgrade``` and let me know if you still have the issue?

**Comment by nickytonline** [comment]
@stewartmccoy #160 needs to be resolved before we can redeploy to prod. If you're just redeploying to meteor.com, it will not be an issue.

**Comment by stewartmccoy** [comment]
@nickytonline I didn't do a meteor upgrade before, so I'll run that and see if it resolves my errors.

**Comment by stewartmccoy** [comment]
@nickytonline I'm going to revert the merge to master. Can you open a PR from nickyt-upgrade-to-meteor-1.x to devel?

**Comment by nickytonline** [comment]
@stewartmccoy I will look at getting the bootstrap3 and less packages working. I have the issue you're talking about on my local now. I must of had bootstrap3-less files still in my project, even though I upgraded. A clean install results in the style issue. For the time being revert on master and I will create a PR to devel.

**Comment by nickytonline** [comment]
@stewartmccoy With nemo64:bootstrap the main LESS file, ```custom.bootstrap.less``` regenerates on a meteor deploy. This is a problem because in our old main.less file, we imported one of our LESS files at the top of the main file and two other imports occur at the end of the old main file. With nemo64:bootstrap, imports are only allowed at the beginning.

For the time being, I created another main LESS file to circumvent this so that I can add our two imports at the end as well, but this is not a clean solution. I'll dig a little deeper for a cleaner solution.

**Comment by stewartmccoy** [comment]
@nickytonline sounds good. Thank you :)

**Comment by stewartmccoy** [comment]
@nickytonline I reverted the merge to master with PR #163.

**Pull request merged**
